/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * coba.java
 *
 * Created on 26 Okt 19, 15:43:41
 */

package Coba;
import java.sql.Connection;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;


/**
 *
 * @author TOSHIBA
 */
public class coba extends javax.swing.JFrame {

    





    /** Creates new form coba */
    public coba() {
        initComponents();
        GetData();
        databaru=true;
    }


    public boolean databaru;
   private void GetData(){ // menampilkan data dari database
    try {
        Connection con =koneksi.getConnection();
        Statement stm = con.createStatement();
        ResultSet sql = stm.executeQuery("select * from employee");
        jTable2.setModel(DbUtils.resultSetToTableModel(sql));
    }
    catch (Exception e) {
    }

}
 
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        txtid = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        RBLK = new javax.swing.JRadioButton();
        RBPR = new javax.swing.JRadioButton();
        txttlp = new javax.swing.JTextField();
        txtalamat = new javax.swing.JTextField();
        cbjabatan = new javax.swing.JComboBox();
        CBgol = new javax.swing.JComboBox();
        txtgaji = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtsave = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(120, 120, 120));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(null);

        txtid.setBorder(null);
        txtid.setOpaque(false);
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        getContentPane().add(txtid);
        txtid.setBounds(540, 134, 250, 20);

        txtnama.setBorder(null);
        txtnama.setOpaque(false);
        getContentPane().add(txtnama);
        txtnama.setBounds(540, 174, 250, 20);

        buttonGroup1.add(RBLK);
        RBLK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RBLK.setText("Laki-laki");
        RBLK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBLKActionPerformed(evt);
            }
        });
        getContentPane().add(RBLK);
        RBLK.setBounds(540, 210, 120, 25);

        buttonGroup1.add(RBPR);
        RBPR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RBPR.setText("Perempuan");
        RBPR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBPRActionPerformed(evt);
            }
        });
        getContentPane().add(RBPR);
        RBPR.setBounds(660, 210, 130, 25);

        txttlp.setBorder(null);
        txttlp.setOpaque(false);
        getContentPane().add(txttlp);
        txttlp.setBounds(540, 250, 250, 20);

        txtalamat.setBorder(null);
        txtalamat.setOpaque(false);
        getContentPane().add(txtalamat);
        txtalamat.setBounds(540, 290, 250, 20);

        cbjabatan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbjabatan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Staf", "Kabag" }));
        cbjabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbjabatanActionPerformed(evt);
            }
        });
        getContentPane().add(cbjabatan);
        cbjabatan.setBounds(540, 330, 130, 20);

        CBgol.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CBgol.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "G/1", "G/2", "G/3" }));
        CBgol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBgolActionPerformed(evt);
            }
        });
        getContentPane().add(CBgol);
        CBgol.setBounds(540, 360, 130, 20);

        txtgaji.setBorder(null);
        txtgaji.setOpaque(false);
        getContentPane().add(txtgaji);
        txtgaji.setBounds(540, 400, 250, 20);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setOpaque(false);
        jTable2.setRequestFocusEnabled(false);
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(130, 580, 940, 150);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Coba/form-1.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 1160, 810);

        txtsave.setText("Save");
        txtsave.setBorder(null);
        txtsave.setOpaque(false);
        txtsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsaveActionPerformed(evt);
            }
        });
        getContentPane().add(txtsave);
        txtsave.setBounds(540, 450, 100, 40);

        btndelete.setText("Delete");
        btndelete.setBorder(null);
        btndelete.setOpaque(false);
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btndelete);
        btndelete.setBounds(690, 450, 100, 40);

        btnexit.setText("Exit");
        btnexit.setBorder(null);
        btnexit.setOpaque(false);
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        getContentPane().add(btnexit);
        btnexit.setBounds(1030, 80, 50, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
    // TODO add your handling code here:
}//GEN-LAST:event_formMouseClicked

private void cbjabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbjabatanActionPerformed
    
}//GEN-LAST:event_cbjabatanActionPerformed

private void RBPRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBPRActionPerformed
    
}//GEN-LAST:event_RBPRActionPerformed

private void RBLKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBLKActionPerformed
    
    
}//GEN-LAST:event_RBLKActionPerformed

private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
    // TODO add your handling code here:
    JOptionPane.showMessageDialog(null, "Anda Keluar ?");
                Login log = new Login();
                log.setVisible(true);
                setVisible(false);
}//GEN-LAST:event_btnexitActionPerformed

private void txtsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsaveActionPerformed
 String jabatan = (String) cbjabatan.getSelectedItem();
 String golongan = (String) CBgol.getSelectedItem();
 String Jenis_Kelamin = null;
 String gaji = txtgaji.getText();
                if(RBLK.isSelected()){
                    Jenis_Kelamin="Laki-laki";
                }else if(RBPR.isSelected()){
                    Jenis_Kelamin="Perempuan";
                }
  if(CBgol.getSelectedItem().equals("G/1")){
                 golongan="G/1";
                 gaji="6800000";
                 }else if(CBgol.getSelectedItem().equals("G/2")) {
                 golongan="G/2";
                 gaji="7200000";
                 }else{
                 golongan="G/3";
                 gaji="8000000";
                  }
    if (databaru == true) { // prosess simpan atau edit
        try {
                String sql = "INSERT INTO employee (id_karyawan,nama_karyawan, Jenis_Kelamin, no_telphone,alamat,jabatan,golongan,gaji) VALUES('"+txtid.getText()+"','"+txtnama.getText()+"','"+Jenis_Kelamin+"','"+txttlp.getText()+"','"+txtalamat.getText()+"','"+jabatan+"','"+golongan+"','"+gaji+"')";
                if(cbjabatan.getSelectedItem().equals("Staf")){
                  jabatan="Staf";
                }else if(cbjabatan.getSelectedItem().equals("Kabag")){
              jabatan="Kabag";

                 }
            Connection con = koneksi.getConnection();
            PreparedStatement pst = con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "berhasil disimpan");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }}
    GetData();

}//GEN-LAST:event_txtsaveActionPerformed

private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_txtidActionPerformed

private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
    // TODO add your handling code here:
    try { // hapus data
        String sql ="delete from employee where id_karyawan='"+txtid.getText()+"'";
        Connection con = koneksi.getConnection();
        PreparedStatement pst = con.prepareStatement(sql);
        pst.execute();
        JOptionPane.showMessageDialog(null, "Data Terhapus");
        databaru=true;
        txtid.setText("");
        txtnama.setText("");
        txttlp.setText("");
        txtalamat.setText("");
        txtgaji.setText("");
       
    } catch (Exception e) {}

    GetData();
}//GEN-LAST:event_btndeleteActionPerformed

private void CBgolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBgolActionPerformed
    String golongan;
    if(CBgol.getSelectedItem().equals("G/1")){
                 golongan="G/1";
                 txtgaji.setText("6800000");
                 }else if(CBgol.getSelectedItem().equals("G/2")) {
                 golongan="G/2";
                 txtgaji.setText("7200000");
                 }else{
                 golongan="G/3";
                 txtgaji.setText("8000000");
                  }
}//GEN-LAST:event_CBgolActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new coba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CBgol;
    private javax.swing.JRadioButton RBLK;
    private javax.swing.JRadioButton RBPR;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnexit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbjabatan;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtgaji;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnama;
    private javax.swing.JButton txtsave;
    private javax.swing.JTextField txttlp;
    // End of variables declaration//GEN-END:variables

   
}
