/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Login.java
 *
 * Created on 29 Okt 19, 19:22:49
 */

package Coba;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
/**
 *
 * @author TOSHIBA
 */
public class Login extends javax.swing.JFrame {
    String username;
    String password;

    /** Creates new form Login */
    public Login() {
        initComponents();
        GetData();
        databaru=true;
        
    }
    public void Login() {
        initComponents();
     GetData1();
        databaru1=true;
    }
    
    public void Login(String a){
        initComponents();
        GetData2();
        databaru2=true;
    }
    public boolean databaru;
    private void GetData(){ // menampilkan data dari database
    try {
        Connection conn =koneksiLogin.getConnection();
        Statement stm = conn.createStatement();
        ResultSet sql = stm.executeQuery("select * from login where username=? and password=?");
    }
    catch (Exception e) {
    }
}
    public boolean databaru1;
    private void GetData1() {
        // menampilkan data dari database
    try {
        Connection conn =koneksiLogin.getConnection();
        Statement stm = conn.createStatement();
        ResultSet sql = stm.executeQuery("SELECT * FROM login1 WHERE user=? and pass=?");
    }
    catch (Exception e) {
    }
    }
public boolean databaru2;
    private void GetData2() {
        try {
        Connection conn =koneksiLogin.getConnection();
        Statement stm = conn.createStatement();
        ResultSet sql = stm.executeQuery("SELECT * FROM login2 WHERE username=? and password=?");
    }
    catch (Exception e) {
    }
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        txtpass = new javax.swing.JPasswordField();
        txtusername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        txtpass.setBorder(null);
        txtpass.setOpaque(false);
        txtpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassActionPerformed(evt);
            }
        });
        getContentPane().add(txtpass);
        txtpass.setBounds(730, 450, 240, 40);

        txtusername.setBorder(null);
        txtusername.setOpaque(false);
        getContentPane().add(txtusername);
        txtusername.setBounds(730, 380, 240, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(949, 703, 69, 17);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Coba/login new-1.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1160, 780);

        btnLogin.setBackground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.setBorder(null);
        btnLogin.setOpaque(false);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin);
        btnLogin.setBounds(690, 530, 120, 60);

        btnexit.setText("Exit");
        btnexit.setOpaque(false);
        btnexit.setOpaque(false);
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        getContentPane().add(btnexit);
        btnexit.setBounds(1030, 60, 60, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        if (databaru == true) { // prosess simpan atau edit
        try {
            String sql = "SELECT * FROM login WHERE username=? and password=?";
            Connection conn = koneksiLogin.getConnection();
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, txtusername.getText());
            pst.setString(2, txtpass.getText());
            ResultSet rs = pst.executeQuery();
            pst.execute();
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "Login Berhasil");
                coba data = new coba();
                data.setVisible(true);
                setVisible(false);
            } else{
                JOptionPane.showMessageDialog(null, "Gagal");
                txtusername.setText("");
                txtpass.setText("");
            }
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
           GetData();

        }else if (databaru1 == true) { // prosess simpan atau edit
        try {
            String sql = "SELECT * FROM login1 WHERE user=? and pass=?";
            Connection conn = koneksiLogin.getConnection();
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, txtusername.getText());
            pst.setString(2, txtpass.getText());
            ResultSet rs = pst.executeQuery();
            pst.execute();
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "Login Berhasil");
                coba data = new coba();
                data.setVisible(true);
                setVisible(false);
            } else{
                JOptionPane.showMessageDialog(null, "Gagal");
                txtusername.setText("");
                txtpass.setText("");
            }
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
           GetData1();

        }else if(databaru2 == true) { // prosess simpan atau edit
        try {
            String sql = "SELECT * FROM login2 WHERE username=? and password=?";
            Connection conn = koneksiLogin.getConnection();
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, txtusername.getText());
            pst.setString(2, txtpass.getText());
            ResultSet rs = pst.executeQuery();
            pst.execute();
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "Login Berhasil");
                coba data = new coba();
                data.setVisible(true);
                setVisible(false);
            } else{
                JOptionPane.showMessageDialog(null, "Gagal");
                txtusername.setText("");
                txtpass.setText("");
            }
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
           GetData2();

        }
    }//GEN-LAST:event_btnLoginActionPerformed

         private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
             // TODO add your handling code here:
             System.exit(0);
         }//GEN-LAST:event_btnexitActionPerformed

         private void txtpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassActionPerformed
             // TODO add your handling code here:
         }//GEN-LAST:event_txtpassActionPerformed
    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnexit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables

}


